### ISSUE TITLE
about environmental issues

### ISSUE THREAD

**Issue by zcswdt** [Murkey8895/foldsformer#3]
Hello, may I ask what is your code environment and the CUDA version? Thank you

**Comment by Murkey8895** [comment]
Hi, I just tested the code on a machine with Nvidia 1660Ti, driver 510.108.03 and CUDA 11.6. It works.

**Comment by zcswdt** [comment]
> 您好，我刚刚在配备 Nvidia 1660Ti、驱动程序 510.108.03 和 CUDA 11.6 的机器上测试了代码。有用。

I ran this code on Ubuntu 20.04 and there were no issues with the installation environment. However, when running softgym, an error was reported. I don't know if it's an issue with Ubuntu 20.04!

![16fe59f28e1047479be4f3963335c11](https://github.com/Murkey8895/foldsformer/assets/43515926/396b0846-9693-4533-8e0a-eaeab16ec84e)

**Comment by Murkey8895** [comment]
We didn't modify any core C/C++ codes in Softgym. So if you can run the code in SoftGym, you can also run the code in this repo. Maybe you could ask this question under [SoftGym](https://github.com/Xingyu-Lin/softgym). As for this error, I think it's because you try to change the GUI's window size, which will cause a segmentation fault, according to my experience.

**Comment by zcswdt** [comment]
> We didn't modify any core C/C++ codes in Softgym. So if you can run the code in SoftGym, you can also run the code in this repo. Maybe you could ask this question under [SoftGym](https://github.com/Xingyu-Lin/softgym). As for this error, I think it's because you try to change the GUI's window size, which will cause a segmentation fault, according to my experience.

Thank you for your reply. I have installed the Ubuntu 18.04 system and can use your code here. Thank you for your help in answering the questions.
